### PR TITLE
Fix-Deprecatd-Gradle-Issues-#9

### PR DESCRIPTION
**Pull request by Jenish-1235**
Fixed-Deprecated-Gradle-Issues.

Project builds successfully now.

### CODE REVIEW

**Comment by Jenish-1235** [comment]
Do review this as soon as possible , as merging this branch with main, will help me to make the new branch that successfully builds the app and I can start working on saving the history of words learnt in past.

**Comment by Sav22999** [comment]
@Jenish-1235 Please, make edits directly in this PR 😄

**Comment by Jenish-1235** [comment]
Definitely, but taking out a separate feature branch, I think will help to keep things organized

**Comment by Jenish-1235** [comment]
And even for hacktoberfest, every separate pr counts

**Pull request merged**
