### PR TITLE
Save word history

### PR DESCRIPTION
**Pull request by Jenish-1235**
Added Feature to save the words learnt in past under the history feature.

### CODE REVIEW

**Comment by Sav22999** [comment]
@Jenish-1235 It doesn't compile to me, I get this error:

> java.lang.IllegalAccessError: superclass access check failed: class org.jetbrains.kotlin.kapt3.base.javac.KaptJavaCompiler (in unnamed module @0x520f5216) cannot access class com.sun.tools.javac.main.JavaCompiler (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x520f5216
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jetbrains.kotlin.kapt3.base.KaptContext.<init>(KaptContext.kt:55)
	at org.jetbrains.kotlin.kapt3.KaptContextForStubGeneration.<init>(KaptContextForStubGeneration.kt:38)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.contextForStubGeneration(Kapt3Extension.kt:295)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:174)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:104)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:104)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:114)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:460)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:62)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:476)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:399)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:280)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:124)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:636)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1598)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Jenish-1235** [comment]
Yes, that's what I was saying. Firstly will need to fix the deprecated gradle issue. 
And updating the android studio and gradle to the latest supported versions as well running agp.

**Comment by Jenish-1235** [comment]
I had fixed the issue in earlier pr. After that, pull this pr and set your project jdk to 17 as latest dependencies are not supporting jdk lower than 17.

**Comment by Jenish-1235** [comment]
@Sav22999 do you have any updates regarding compilation issue?

**Comment by Sav22999** [comment]
@Jenish-1235 I've tried to compile but it did't work.

Rebase this PR from the main

I got this error:
```

java.lang.IllegalAccessError: superclass access check failed: class org.jetbrains.kotlin.kapt3.base.javac.KaptJavaCompiler (in unnamed module @0x28f51485) cannot access class com.sun.tools.javac.main.JavaCompiler (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x28f51485
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jetbrains.kotlin.kapt3.base.KaptContext.<init>(KaptContext.kt:55)
	at org.jetbrains.kotlin.kapt3.KaptContextForStubGeneration.<init>(KaptContextForStubGeneration.kt:38)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.contextForStubGeneration(Kapt3Extension.kt:295)
	at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:174)
	at org.jetbrains.kotlin.kapt3.ClasspathBasedKapt3Extension.analysisCompleted(Kapt3Extension.kt:104)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM$analyzeFilesWithJavaIntegration$2.invoke(TopDownAnalyzerFacadeForJVM.kt:104)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:114)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:256)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:247)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:87)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:460)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:62)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:476)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:399)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:280)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:124)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:636)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1598)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Errors were stored into /Users/sav/Documents/GitHub/Sav22999/word-of-the-day/.gradle/kotlin/errors/errors-1728503744675.log
```

**Comment by Jenish-1235** [comment]
You won't have to rebase this pr. Just use jdk 17 and add all the dependecies in module level build.gradle file.

**Comment by Sav22999** [comment]
@Jenish-1235  Try to merge the main to this PR, you'll probably get the same error

**Comment by Jenish-1235** [comment]
Firstly, you will need to review the fixed-gradle-issue pr. I fixed deprecated gradle issues in that pr and added required dependencies. After that, you have to use jdk 17 in project.

After reviewing for fixed-gradle-issue pr , we can move to save-word-history pr. 
Attaching screenshot of feature devloped.

**Comment by Sav22999** [comment]
@Jenish-1235 I already have merged the PR #10

**Comment by Jenish-1235** [comment]
Could you send me your current build.gradle files and screenshot of jdk you are using?

**Comment by Jenish-1235** [comment]
Or just can you reset your current branch to this commit.

https://github.com/Sav22999/word-of-the-day/commit/484ca410bb1f90832b7180c640adab25cce09189

**Comment by Sav22999** [comment]
@Jenish-1235 Resetting to the #484ca41 it didn't show to me the new feature

**Comment by Sav22999** [comment]
@Jenish-1235 In the new View, there is the back button missing (to go to back to the home)

**Comment by Jenish-1235** [comment]
Oh , thanks for pointing out. I will add one very soon.

**Comment by Jenish-1235** [comment]
Could let me know, if things right now are working fine or not?

**Comment by Jenish-1235** [comment]
so basically, you are currently able to see the history feature right?

**Comment by Sav22999** [comment]
@Jenish-1235 Yes, exactly

**Comment by Jenish-1235** [comment]
So my next task is to add back button, I will do it within few hrs after my school.

**Comment by Jenish-1235** [comment]
ohkay, then could you merge this pr and add hacktoberfest-accepted labels as I have to complete hacktoberfest before 12th October to get certifications from my university. That's my challenge task.

**Comment by Sav22999** [comment]
If you add the new button in the next hours I'll merge the PR tomorrow in the morning 😊

**Comment by Sav22999** [comment]
Another feedback:

The icon, a bit more bigger (similar to the Settings/copy/share one)

**Comment by Jenish-1235** [comment]
Sure , I will add it within few hrs. Probably within next 6 hrs.

**Comment by Jenish-1235** [comment]
@Sav22999 Added Back button, date for word and increased size of icons as mentioned.

**Comment by Sav22999** [comment]
Now it doesn't compile again.

Compiling error:

```
Task :app:kaptGenerateStubsFDGHDebugKotlin FAILED
e: java.lang.IllegalAccessError: superclass access check failed: class org.jetbrains.kotlin.kapt3.base.javac.KaptJavaCompiler (in unnamed module @0x342932a8) cannot access class com.sun.tools.javac.main.JavaCompiler (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x342932a8
```

**Comment by Jenish-1235** [comment]
> compiler does not export com.sun.too

I guess this is happening because both of us are might be using different jdk versions. Could you tell me what jdk and gradle version are you using. As this compiles successfully at my side.

**Comment by Sav22999** [comment]
@Jenish-1235 Jdk (21) of JetBrains (I don't have now the pc, so I cannot give you exactly this information now.

I've tried also with other sdk anyways

**Comment by Jenish-1235** [comment]
Once try with jdk 17.

**Comment by Sav22999** [comment]
@Jenish-1235 Same problem also using jdk 17

**Comment by Jenish-1235** [comment]
Give me 5 mins, I will just revert back the to your last working commit and make changes on top of that

**Comment by Jenish-1235** [comment]
@Sav22999 Upon resetting to the last working commit for you 

I get this error


java.lang.IllegalAccessError: superclass access check failed: class org.jetbrains.kotlin.kapt3.base.javac.KaptJavaCompiler (in unnamed module @0x38b4d9ca) cannot access class com.sun.tools.javac.main.JavaCompiler (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.main to unnamed module @0x38b4d9ca

**Comment by Jenish-1235** [comment]
Now , If I pull my 2 commits on same branch that I made afterwards. The Project is again getting built succesfully.

**Comment by Jenish-1235** [comment]
@Sav22999 try building now , after merging my latest commit. I replaced the dependency which was raising compilation error i.e kapt with ksp. Now, it builds completely fine with any jdk and agp. I tried it out with jdk 11, 17 and 21.

**Comment by Sav22999** [comment]
@Jenish-1235 Good! Now it compiles.
I've made some improvements, but there is a bug with the new Word History Activity

image

image

Fix this last bug and I'll merge the PR 😄

**Comment by Sav22999** [comment]
@Jenish-1235 I've just seen words are duplicated:

image

**Comment by Jenish-1235** [comment]
Sure , within few minutes

**Comment by Jenish-1235** [comment]
Hey, dude. Words are not getting repeated on same codebase. Could you uninstall and rebuild the app once again. On my side, it is working completely fine.

**Comment by Jenish-1235** [comment]
Look forward by pulling after this commits. It should work good now.

**Comment by Sav22999** [comment]
@Jenish-1235 The bug is preset yet 😢

**Comment by Jenish-1235** [comment]
@Sav22999 Fix top bar app bug too.

**Comment by Sav22999** [comment]
@Jenish-1235 Not fixed yet

**Comment by Jenish-1235** [comment]
Could you show a screenshot?

**Comment by Sav22999** [comment]
@Jenish-1235 Sure, this is the screenshot:

image

**Comment by Sav22999** [comment]
(and if you fix the bar, I ask you also to sort the words learnt from the newer to oldest (newest at the top), so I avoid to do a commit just with this edit 😄

**Comment by Jenish-1235** [comment]
Sure I will do it

**Comment by Sav22999** [comment]
@Jenish-1235 Perfect about the sorting... but the topbar is not fixed, you've just put programmatically a padding-top, which is not the solution

**Comment by Sav22999** [comment]
@Jenish-1235 I've fixed the topbar for you. I can merge the PR now

**Comment by Jenish-1235** [comment]
Thanks dude.

**Pull request merged**
